### ISSUE TITLE
Some insight I found but I don't know if it will help you

### ISSUE THREAD

**Issue by thakyZ** [lukahn/Square-Enix-Software-Token-OTP#1]
Been looking to see if there was a way to extract the TOTP token and stumbled upon this repo.
I found a file in `/data_mirror/cur_profiles/0/com.square_enix_software_token` called primary.prof. It appears to be an encoded file with a data heading of `pro010`

**Comment by lukahn** [comment]
Heya @thakyZ , thanks for dropping by! Hopefully together we can work out how to extract (or regenerate) the TOTP code.
I don't have a `/data_mirror` location on my devices (I'm not sure if this is a LineageOS thing), but I wasn't able to find the `primary.prof` file anywhere. An old WhatsApp backup of mine has this file though, so maybe it's a generic profile config file.

There are a few other files that the app generates when registering for TOTP relating to nonce values, so I'll update the README.md to list those. Maybe they would be useful.

Otherwise I'm just (slowly) in the process of trying to debug the app in Android Studio to hopefully find out how the `/data/data/com.square_enix_software_token/files/VDS_dfms4142` file is read, decrypted, used, then re-encrypted. My guess (hope) is that this file has the HOTP parameters (secretKey, counter). Otherwise it should at least give some insight into the custom implementation that DP4Mobile uses.

**Comment by thakyZ** [comment]
Ah okay, no I just have stock Google Pixel - Android 10 but rooted with Magisk, but thank you for letting me know.

Also, I did find the file you mentioned, but I have zero knowledge on it, but again I hope the best on your endeavors, and I'll be watching this for any future updates.

**Comment by lukahn** [comment]
Sounds good, thanks for having a look :)
It turns out that the nonce file was to do with WebView, and not related to the encryption functionality of the app.
I've also found out that the first four characters of the file `VDS_dfms4142` are the version number (currently from 0001 - 0004), so I'm working on the older version hoping it'll be simpler. I suspect that this file is an encrypted XML blob given some of the libraries in the app, with some sort of timestamp embedded that makes it change after each OTP generation.
The file gets decrypted when the app is loaded (as an empty file puts the user back at the first EULA screen), so that's the area that I want to focus on for now. I couldn't find a way to run the smali code (with breakpoints), so I'm just fumbling around with Android Studio and hoping that I can get some debugging info from that.
Hopefully I'll have some good news for you before too long.

**Comment by lukahn** [comment]
Hi @thakyZ ,
Just wanted to give you a quick update to say that as of three days ago, regular software authenticators can now be used instead of the SQEX app. :)

**Comment by thakyZ** [comment]
Thank you so much I wouldn't have realized that tbh
